import { Html, Head, Main, NextScript } from 'next/document';

export default function Document() {
  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by Ezequiel Rivas" />
        <link
          href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap"
          rel="stylesheet"
        />
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Splash&display=swap"
          rel="stylesheet"
        /> */}
        {/* <link
          href="https://db.onlinewebfonts.com/c/a6db4fb3cf727e10e461d11f5b3349f0?family=Northwell"
          rel="stylesheet"
          type="text/css"
        /> */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@xz/fonts@1/serve/plus-jakarta-display.min.css"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter&display=optional"
          rel="stylesheet"
        />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
